spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  activiti:
  #自动检查、部署流程定义文件
    check-process-definitions: true
  #自动更新数据库结构
    database-schema-update: true
  # asyncExecutorActivate是指activiti在流程引擎启动就激活AsyncExecutor,异步：true-开启（默认）、false-关闭
    spring.activiti.async-executor-activate: true
    history-level: full
    db-history-used: true
  #流程定义文件存放目录,要具体到某个目录
    process-definition-location-prefix: classpath:/processes
  #process-definition-location-suffixes: #流程文件格式
  #  - **.bpmn20.xml
  #  - **.bpmn



server:
  port: 8990
  servlet:
    context-path: /activiti

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cao.activti.mapper

